### ISSUE TITLE
Struct 'DefaultValues' is private and cannot be referenced from a default argument value

### ISSUE THREAD

**Issue by MaeseppTarvo** [fxm90/GradientLoadingBar#1]
Hey, in the `GradientLoadingBar` class there is the following error:

> Struct 'DefaultValues' is private and cannot be referenced from a default argument value

I am using Xcode 9 and the 1.1.4 version of your library.

**Comment by fxm90** [comment]
Sure I can make the struct ```DefaultValues``` public. But why do you need to access it? Actually for calling ```GradientLoadingBar``` you don't need to provide the default argument values?

**Comment by MaeseppTarvo** [comment]
@fxm90 not that I need it but the Xcode is throwing an error inside the library's GradientLoadingBar class.

**Comment by fxm90** [comment]
Okay, unfortunately I didn't get that error with Xcode 9 🤔 But I will release a (possible) bugfix now.

**Comment by fxm90** [comment]
``` 🚀  GradientLoadingBar (1.1.5) successfully published```

Could you please update and try again?
