### ISSUE TITLE
Observable Extension missing argument for parameter #2 in call

### ISSUE THREAD

**Issue by chienplee** [fxm90/GradientLoadingBar#10]
Hi,

Thanks for the great library. Currently using 1.1.12 and Observable 1.4 which was updated 2 days ago.
The file `Observable + ObserveDistinct.swift` cannot be compiled with the error message `'Missing argument for parameter #2 in call'`. Any workarounds for now until the next update? Thanks.

Environment: Xcode 10
Swift version: Swift 4.2

<img width="983" alt="2018-11-14 7 30 10" src="https://user-images.githubusercontent.com/16417906/48479934-c461d980-e843-11e8-91ca-228b7008c046.png">

**Comment by fxm90** [comment]
Hello @chienplee,

thanks for reporting this Bug 👍 
I've just published a new version, could you please try running `pod update GradientLoadingBar` ? 🙂

**Comment by chienplee** [comment]
Hello, yes it works!! Thank you very much :)
