### ISSUE TITLE
iPad Pro 12.9 hasNotch is true

### ISSUE THREAD

**Issue by prisacariugeorge** [fxm90/GradientLoadingBar#20]
Hi,
There is a problem with the hasNotch check, because the iPad Pro 12.9-inch has safeAreaInsets 20
https://developer.apple.com/forums/thread/110724
Thanks.

**Comment by fxm90** [comment]
Thanks for pointing this out 👍 I can reproduce the issue and will work on a fix.

**Comment by fxm90** [comment]
Sorry I've been busy on the weekend. I've pushed a fix to `bug/20-fix-notch`. Can you install the version from that branch and test if it works? Thanks :)

**Comment by prisacariugeorge** [comment]
Hi,
I've installed the branch and it works on the iPad 12.9-inch now.
Thanks.

**Comment by fxm90** [comment]
Nice, thanks for testing 👍  I'll publish a new version soonish.

**Comment by fxm90** [comment]
I've released a new version (2.1.1) containing the fix.
