### ISSUE TITLE
iphone 13 notch

### ISSUE THREAD

**Issue by calebmitcler** [fxm90/GradientLoadingBar#23]
does there need to be work done for the new notch size on iPhone 13?

**Comment by fxm90** [comment]
Yes there are some adaptions that needs to be done 👍 

I already started working on this, but did not find the time to finish it properly (some clean-up is still needed). You can already try the updated loading bar by installing the version from ` feature/adapt-notch-size-for-iPhone-13`. It should have the correct size for the iPhone 13 notch.

**Comment by fxm90** [comment]
Fixed in Version 2.2.0
