### ISSUE TITLE
Cannot find 'UIDevice' in scope

### ISSUE THREAD

**Issue by OnurVar** [fxm90/GradientLoadingBar#24]
Hello,

I just downloaded v2.2.0 using SPM and it seems like `UIKit` is missing on `NotchGradientLoadingBarViewModel.swift`

Best regards

![image](https://user-images.githubusercontent.com/4017312/135950485-eacd6da3-1485-4cb6-85e0-38b4e2a8c524.png)

**Comment by fxm90** [comment]
Thanks for reporting 🙏 `UIDevice` is definitely part of `UIKit`, weird that the project was compiling for me though 🤔 

Anyhow, I've just released version `2.2.1` containing the correct import 👍 

<img width="575" alt="image" src="https://user-images.githubusercontent.com/17249312/135973715-9ef62565-050a-4708-87f9-5df6f9a70e01.png">

**Comment by OnurVar** [comment]
Thanks for the quick fix. It was also working on my project using cocoapods. But when I switch to SPM from cocoapods, it failed. I believe this is because of the way cocoapod handles uikit framework. 

Best regards

**Comment by fxm90** [comment]
Thanks for explaining 👍 Just searched for two seconds on Google, and there is already a Medium article about that issue: [UIKit is currently being imported by CocoaPods in iOS-targeted Pods](https://medium.com/@romainbertozzi/uikit-is-currently-being-imported-by-cocoapods-in-ios-targeted-pods-4a3e07553000) 😄
