### ISSUE TITLE
Notch Bar is displayed wrong on iPhone 11 Pro Max

### ISSUE THREAD

**Issue by alinfarcas12** [fxm90/GradientLoadingBar#29]
Hello! There seems to be a problem on the iPhone 11 Pro Max with the notch bar.
![Screenshot 2022-05-09 at 12 06 36](https://user-images.githubusercontent.com/62880976/167377803-fb8e0d63-85bf-47dc-aabd-2d75b5e6a256.png)

**Comment by fxm90** [comment]
Thanks for reporting, I've just released version 2.3.1 with a fix 👍
