### ISSUE TITLE
iPhone X Compatibility

### ISSUE THREAD

**Issue by kuraydev** [fxm90/GradientLoadingBar#4]
Hello,
I would like to use this awesome library but I could not figure it how to solve iPhone X Layout compatibility. Can you share your solution if it is already working with iPhone X layout ? 
Thank you :)

**Comment by fxm90** [comment]
Hello, is this desired layout you're looking for?

![image](https://user-images.githubusercontent.com/17249312/34354471-c5f79a8c-ea2e-11e7-8ffe-00911de2e3ab.png)

**Comment by kuraydev** [comment]
@fxm90  Kinda yes, is it available right now? Because I could not make it :(

**Comment by fxm90** [comment]
@WrathChaos Kinda yes or yes? 😄 I could release a new version supporting iPhone X with the above layout during the next days.

**Comment by kuraydev** [comment]
@fxm90 Yes yes :D Thank you so much ! :) Waiting for it :O

**Comment by fxm90** [comment]
@WrathChaos I've just released version 1.1.7 - waiting for your feedback :)

**Comment by kuraydev** [comment]
@fxm90 Love you maaan! Thank you so much, I will check this version within 3 days.

**Comment by fxm90** [comment]
@WrathChaos Any update? 😄

**Comment by kuraydev** [comment]
@fxm90 Really sorry, I was too busy during last 2 weeks.. You're rock! :) Thank you again

**Comment by kristoff2016** [comment]
Hi thanks for nice lib 

" I've just released version 1.1.7 - waiting for your feedback :)" released ?

Thank you so much  I like this plugin man
