### ISSUE TITLE
Does it work with UINavigationController ?

### ISSUE THREAD

**Issue by kristoff2016** [fxm90/GradientLoadingBar#5]
Hello thanks again for nice plugin,

it did not show anything for me 
I followed your example : GradientLoadingBar.shared.show() 

thanks

**Comment by fxm90** [comment]
@kristoff2016 Should also work with a `UINavigationController`. You could try to debug the view hierarchy, to see if `GradientLoadingBar` gets attached to the correct view.

**Comment by rohaaa** [comment]
@kristoff2016 @fxm90 the same problem, i've tried self.navigationController?.view, but can't attach it to the top of the screen. Did you find a solution?

**Comment by fxm90** [comment]
@rohaaa I‘ve just tested it using navigation controller and it‘s working fine (without applying any custom superview at all) 🤔

**Comment by rohaaa** [comment]
@fxm90 you're right everything works perfectly :) I just had to remove onView: that I thought I needed. Thank you!

**Comment by fxm90** [comment]
You're welcome :)
@kristoff2016 Any update?

**Comment by kristoff2016** [comment]
Hi thanks for your nice work. your libs is worked perfectly but that my mistake and able to fixed it

thanks
